### ISSUE TITLE
Add new "special" car

### ISSUE THREAD

**Issue by 42MonthsAfter** [42MonthsAfter/server#10]
Community member Boomin4u as recommended having a special car on the server that there is only one of. It can only be won via competition. 

It could get claimed via 5 finger discount.

**Comment by Bigboss8225** [comment]
I feel like this would open the door for "special" items on a big scale. 
"Special" Car, then "Special" Gun, "Special" Heli, "Special" boat....etc

**Comment by 42MonthsAfter** [comment]
Added the GAZ this round of updates but it is buggy. Mr Wolf found out the hard way. Will look into fixing it and get back to you all.

**Comment by MrWolfGaming** [comment]
It was a nice car, very slow in terms of turning and braking but it can drive over most things. Road blocks? that car dont care ^^

**Comment by MrWolfGaming** [comment]
but still like the LR a bit more. But the new car is a car for Mrs Wolf ^^

**Comment by 42MonthsAfter** [comment]
So we can close this out, we added two!
