### ISSUE TITLE
server dont show up in steam luncher

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#115]
Cant seem to find the server again on steam luncher but can find it on stand alone luncher

**Comment by 42MonthsAfter** [comment]
We sadly don't have any control over this. Other servers were having similar issues, turns out its something with steam (at least as far as I have read).

**Comment by MrWolfGaming** [comment]
Okidoki. Good to know. Still want me to report when it happens or shall I ignore it as long as it works on the stand alone?
