### ISSUE TITLE
green house

### ISSUE THREAD

**Issue by Mrswolf1becausemrswolfwastaken** [42MonthsAfter/server#122]
So everything i planted dissaperd really fast again. I dont know if that how it is gonna be or if it is still bugging. 

Mrs Wolf

**Comment by 42MonthsAfter** [comment]
I think we finally solved it!!! There was a type for "greenhousegardenplots" that had a typo in it so I couln't find it.

Was able to change it from 7200 to 3888000 (server max, 45 days).

Should roll out with the next restart. Suggest planting a couple small things and seeing if they stick around. I will be testing myself.
