### ISSUE TITLE
Gun Cleaner Kit at trader

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#16]
So i did buy 3 Gun Cleaner Kit at the trader and i did only get 1 of 3 and the one i did get did only have 1 use on it.

**Comment by Galaxy-Panda** [comment]
it's an issue with the way the number system is set up for trading.

**Comment by 42MonthsAfter** [comment]
Updated in the 7.5.3 update. Price and availability are updated.
