### ISSUE TITLE
issues in game.

### ISSUE THREAD

**Issue by Galaxy-Panda** [42MonthsAfter/server#17]
before restart i was looting with a mvs rucksack in my hands with mvs gear in it, game crashed and logged in after restart and the back was gone and the gear inside.

Also, i bought meat in the trader ( Venison, chicken, and fish fillet). when i cooked and smoked it with the barrel it was fine but when i went to eat it, its was instantly done eating and only gave me up arrows on food for 2 seconds and went back down.

**Comment by Galaxy-Panda** [comment]
Also, i seems that if you change the quantity of what you are purchasing, the shop will charge you as if you bought that much but will only give 1.

**Comment by Galaxy-Panda** [comment]
ok so i see now that the trader.... if strawberry jam has a quantity of 300 in a jar, then when the trader is limited to 100 then when that is full, you can't even buy and entire jar. understand what im saying? i can explain it better in over voice.

**Comment by 42MonthsAfter** [comment]
I get it, sounds like the trader doesn't sell full amounts by default. I will look into it.

I had to go over every single magazine and make sure they were being sold full, didn't think to look at food. Thanks for the heads up.

As for your bag, if you crash and lose it, you crash and lose it. Sadly part of the game.

**Comment by 42MonthsAfter** [comment]
Should be resolved in the future because of a fix in 7.5.3

Let me know if you still this issue in game

**Comment by 42MonthsAfter** [comment]
Also in the future please do one issue per...well... issue. be descriptive in the title so others are less likely to resubmit.
