### ISSUE TITLE
MunghardsItempack lagg freeze issue?

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#25]
So i notised that when you added MunghardsItempack to the server the game started "Server lagg" alot.
Like befor it was added the freezing mid driving and then tp around only happed like 4-6 times sens we change map.
But sens you added it to the game it has happen more then 8 times in just a few hours

**Comment by 42MonthsAfter** [comment]
So I think it was actually the expansion mod core that was giving us so much trouble.

I installed each mod one and a time and everything was fine together until I got to that step. Removing all the expansion mods helped. Let me know if you are still seeing an issue here.

**Comment by MrWolfGaming** [comment]
The big "Server lags" was on the old map to and you did add the MunghardsItempack before the expantion mod.
So still not fully sure that it is or is not that mod that made it less stabel.
Can always try using it again and see ^^
