### ISSUE TITLE
Till can´t do anything in the game

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#27]
Both me and Mrs Wolf can still not do anything in the game and when we try relog we cant connect again.

I have tryed to reinstall the mods, reinstall the game and nothing works,

I think our chars got bugged out last night some how.
Dont know what i cant do to fix it

**Comment by 42MonthsAfter** [comment]
How has this been since the rebuild / update? Are you still having these issues?

**Comment by MrWolfGaming** [comment]
it worked lika a charm. Not a singel "server lag" the hole evening 💯
