### ISSUE TITLE
RP character bio issue

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/server#28]
![Screenshot 2021-05-05 015714](https://user-images.githubusercontent.com/83690102/117101947-44969500-ad45-11eb-8a5d-dc9fba0506d2.png)

 ^ This link is broken :/

![image](https://user-images.githubusercontent.com/83690102/117102017-67c14480-ad45-11eb-9086-da3478a00eb1.png)

**Comment by 42MonthsAfter** [comment]
Hmmm.... I'll give into this tonight.

**Comment by 42MonthsAfter** [comment]
Updated the wiki and the !rp command in discord with the proper link.
