### ISSUE TITLE
Can´t finde the server on Steam luncher

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#33]
So some of us cant finde the server in Steam.
Hade to connect thru Direct connect and add and load the mods manualy.

I have tryed re-installing Steam, Re-installed the mods, Restarted my routers, Reset my routers and even turning of all the firewalls and anti-virus on my pc and routers.

Any idé what it can be?

**Comment by MrWolfGaming** [comment]
Can still not finde the server in the luncher. But direct connect still works

**Comment by 42MonthsAfter** [comment]
Is this still the case? I saw that you pointed it out in Discord that you could see it again.

**Comment by MrWolfGaming** [comment]
This is fixed now atlest for us
