### ISSUE TITLE
Trader bug

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#34]
I did find out that the Garden Lime can be sold how many times you want the trader dont take it out of your bags

**Comment by MrWolfGaming** [comment]
sold like 100 of them and only hade 1 one me

**Comment by 42MonthsAfter** [comment]
Thanks for the heads up I'll look into it.

**Comment by MrWolfGaming** [comment]
NP  m8😊

**Comment by 42MonthsAfter** [comment]
Closing out and combining with other issue
