### ISSUE TITLE
50 Russan Rubel Wad

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#36]
Got this item in one of the tents and it cant not be unpacked. Have unpacked this one 5 times not :P

**Comment by 42MonthsAfter** [comment]
I believe you spend it, you don't unpack it

**Comment by MrWolfGaming** [comment]
Ahh but it says unpack if you hold it

**Comment by MrWolfGaming** [comment]
notised that you cant use them. If i have just thos in my inventory and use the trader it says i have 0 money

**Comment by 42MonthsAfter** [comment]
Ok, I will need to remove them from the game then. I'll trade you for some "real" cash next time we are in game.
