### ISSUE TITLE
Stuff despawned while flag was up

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#38]
All the new storege items like 2 side weapon rack, military creats, wardrobe m.m has despawed even tho we hade a flag up.
all our stuff is gone again.

**Comment by 42MonthsAfter** [comment]
Believe this was fixed with the 8.0.1 update. Please let me know if you're still seeing this issue!

I tested several times at my in world hidden spot and things are still good on my end since the update.

**Comment by MrWolfGaming** [comment]
Okidoki will report back if they despawn

**Comment by 42MonthsAfter** [comment]
Should be resolved with the 8.0.3 update.
