### ISSUE TITLE
Trading bills for bigger bills$

### ISSUE THREAD

**Issue by Galaxy-Panda** [42MonthsAfter/server#42]
In the sell section in the food trader, you can sell your $1s, 5s, 10s, and 100s each for bigger dollar amounts. but when you are selling and buying things the game will give you 2s and 20s that you can not trade for anything. they simply do not show up in the sellable items in the trader.

**Comment by 42MonthsAfter** [comment]
A fix will be rolled into the 8.0.4 update that rolls out tonight.
