### ISSUE TITLE
Land Rover despawned

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#44]
So my Land Rover did despawn sadly. Just loged in to check befor bedtime and it was gone

**Comment by MrWolfGaming** [comment]
The Land Rover has not despawnd but the last one did despawn when we where not online so cant tell yet if it is going to stay.
I did empty it in case it will despawn

**Comment by 42MonthsAfter** [comment]
I think we solved this! let's close out this ticket and hope for the best!
