### ISSUE TITLE
4 Door Locker Despawn

### ISSUE THREAD

**Issue by GutsyGeisz** [42MonthsAfter/server#45]
4 Door Locker Despawned after restart with loot in the locker.

**Comment by MrWolfGaming** [comment]
same with this one

**Comment by 42MonthsAfter** [comment]
I believe I have this resolved, found the life was set to the same for the kit as for the deployed, extended deployed time to 45 days (game max)

This was part of the adhoc update to day, please continue to monitor and let me know if it is still an issue.  Will leave open for a week.

**Comment by MrWolfGaming** [comment]
The storage units are still despawning.
Did put out 2 at the begining of the night and when we did come back now they where gone again.

**Comment by MrWolfGaming** [comment]
The Gun rack and tool thingy thingy have not despawnd today so far.

**Comment by 42MonthsAfter** [comment]
Believe we have this solved! 8.0.4 update got it covered!
