### ISSUE TITLE
Wardrobe Despawned

### ISSUE THREAD

**Issue by GutsyGeisz** [42MonthsAfter/server#46]
Wardrobe despawned after restart with loot in it.

**Comment by MrWolfGaming** [comment]
ours also despawnd

**Comment by 42MonthsAfter** [comment]
Closing as it is a duplicate ticket. Original response:

I believe I have this resolved, found the life was set to the same for the kit as for the deployed, extended deployed time to 45 days (game max)

This was part of the adhoc update to day, please continue to monitor and let me know if it is still an issue.  Will leave open for a week.
