### ISSUE TITLE
Lost Some Items

### ISSUE THREAD

**Issue by NastyNerg** [42MonthsAfter/server#49]
lost locker and storage items including vehicle and stuff recovered from event

**Comment by 42MonthsAfter** [comment]
Duplicate ticket, closing. Will continue to monitor for 7 days. Other ticket response: 

I believe I have this resolved, found the life was set to the same for the kit as for the deployed, extended deployed time to 45 days (game max)

This was part of the adhoc update to day, please continue to monitor and let me know if it is still an issue.  Will leave open for a week.
