### ISSUE TITLE
Trollycart despawnd

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#52]
Trollycart was awsome but sadly i did despawn at base while i was sleeping

**Comment by MrWolfGaming** [comment]
fun thing is that stuff seams to not despawn untill you use them. Like the trollycart was in the tent for a wile and did not despawn but after we did drive it to base it did despawn

**Comment by 42MonthsAfter** [comment]
Should be resolved with 8.0.5
