### ISSUE TITLE
Sell USD at trader

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#54]
blue collar boys gaming tryed to sell USD at the trader but dident get anything for it but lost the USD

**Comment by 42MonthsAfter** [comment]
Like, trying to combine his bills? Selling 5 $20 for a $100? Not sure I follow.

**Comment by MrWolfGaming** [comment]
In the food trade you can sell USD. Blue tryed and his money was taken but dident get anything in return. Don't know why you can sell money but apparently you can sell them and not getting anything
