### ISSUE TITLE
Login message 

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#55]
the login message is showing up wroung info
![image](https://user-images.githubusercontent.com/81928410/119016580-65442900-b99a-11eb-8b63-ccb264ac2d9d.png)

**Comment by 42MonthsAfter** [comment]
I saw that yesterday! I think it's an error in the CF tools (GameLab) updates that got pushed earlier this week. 

I reported a bug with them, hopefully they get it to it quickly!

**Comment by 42MonthsAfter** [comment]
Fixed with latest round of bug updates.
