### ISSUE TITLE
All our guns are gone from gun racks and rifel safes

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#58]
Manage to login even tho we cant find the server but when we got in all the guns that we hade in the gun racks and storage where you can store guns is gone, both vanilla and mod guns. Hand guns are still there so it is only AR, SPR and Rifels that are gone. Also all the mags in the inventory of the unit is also there.

So it is only in the slots for the biggers guns and nothing els that is affected

**Comment by 42MonthsAfter** [comment]
Let me know what I can get you back.

This is super weird, literally nothing has changed that should touch those tables. I'll dig into it tonight.

**Comment by 42MonthsAfter** [comment]
So interestingly, my guns are still here in the same cases. 

Sure you weren't looted?

**Comment by MrWolfGaming** [comment]
The only thing we got a bit sad about was one of the honeybadger and the wolf ak guns they rest is will come in time 😊

The weirdest thing is that the hand guns and mags are still in thos units. It is only they bigger guns in the gun slots that is gone.

It happend to the single gun rack. 2 side gun rack and rifle safes. Dident check the tool bench of the tools was still in the tool slots

**Comment by MrWolfGaming** [comment]
Yea the gate was still locked, rifle safe was still locked and would be strange to take the guns but not the mags for them

**Comment by MrWolfGaming** [comment]
The LR, GAZ, M3S and everything else seems to be there still

**Comment by 42MonthsAfter** [comment]
![Screenshot 2021-05-21 203628](https://user-images.githubusercontent.com/75148695/119209398-634e9880-ba74-11eb-8e27-7e851ea3b2fb.png)

Interestingly, I can't ADD new guns to the gun safe (MSP mod). Must be a bug on the mod end, will report to the creator's Discord.

**Comment by 42MonthsAfter** [comment]
Also just logged a bug that might be related, I had some plants growing in a MSP mod greenhouse and they are gone.  Leaning more and more on this being a MSP mod issue.

**Comment by MrWolfGaming** [comment]
Ahh well we dident lose everything so let's wait and se what they say

**Comment by 42MonthsAfter** [comment]
Checking in to see how this has been since the 9.0 update?

**Comment by MrWolfGaming** [comment]
So far all is really good on the server with MSP mod 😊

**Comment by 42MonthsAfter** [comment]
Great! Going to close these tickets out then!
