### ISSUE TITLE
Swap item dissappear 

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#6]
Did swap my honey bager with one of the mre foods and the weapon just disappeared from my inventory and was not in the vicinity

**Comment by 42MonthsAfter** [comment]
When you say swap, how did you do it? Did you hotkey return your gun to your inventory?

Was the MRE in your inventory or was it on the ground?

**Comment by MrWolfGaming** [comment]
The mre food was in my LR and i hade the gun in my hands. I did just pull the food in to my hands without removing the gun, like i have done so many times before.

**Comment by 42MonthsAfter** [comment]
Thats super weird, will try to recreate on my own.

Actually, if the next time you're in if we could try to recreate that would be awesome. And I'll get you back your gun. ha

**Comment by MrWolfGaming** [comment]
i will help you recreate it ^^ i will keep on swaping items from hand with item from the car

**Comment by MrWolfGaming** [comment]
So i made it happen again. so for it only happens with the HB BLK and only when i swap it with "wrapped poppy seed cake" will do some more testing but so far 2 HB BLK

**Comment by 42MonthsAfter** [comment]
If you're able to test again, can you make sure you have spot enough in the storage you'll pulling the MRE from?

Might be like the trader bug where if you don't have room for it, it just disapears

**Comment by MrWolfGaming** [comment]
There was space in both my bags and in the car, alot of space. if i do it with the HB gold or anyother gun it just gos in to the car on in to one of the bags in the car

**Comment by 42MonthsAfter** [comment]
So turns out this is a DayZ bug, we sadly aren't able to fix on our end.
