### ISSUE TITLE
Barrels in M3S

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#62]
All 4 of my barrels in the M3S has despwand with all the loot in them.
Dont worry about the loot. we can get new

**Comment by 42MonthsAfter** [comment]
As a standard rule, shouldn't use vehicles as storage!

Let me know what you lost, I'll get you back.

**Comment by MrWolfGaming** [comment]
It is okay we will find new stuff. Just wanted you to know cus it was weird that is was only the barrels the went missing

**Comment by 42MonthsAfter** [comment]
Fixed with latest round of despawn bug updates.
