### ISSUE TITLE
Lether sewing kit at trader

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#64]
So i tryed to buy 10x kits and i did only get 1 with 1 use left and also if i try to buy 1x after i dont get any at all

**Comment by 42MonthsAfter** [comment]
Buy 10 by just hitting the buy button ten times in a row?

Were there 10 available? Just confirming.

**Comment by MrWolfGaming** [comment]
There was 89 in stocks and I did try to buy 10 in one buy and only got 1. Then I tryed to buy 1 and got 1 but still only 1 use left on them

**Comment by 42MonthsAfter** [comment]
Fixed with latest round  bug updates.
