### ISSUE TITLE
5 milion dollars

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#65]
The trader have spit out 5 milion dollars on the ground. I did pick it up for you or do you want me to burn it.
It was laying on the ground outside the tools trader

**Comment by 42MonthsAfter** [comment]
WHAT? hahaha, appreciate you letting me know!

**Comment by MrWolfGaming** [comment]
Ofc man lucky it was me finding it. Shall I destroy it or bring it to you?

**Comment by 42MonthsAfter** [comment]
I appreciate you burning it man!!!!
