### ISSUE TITLE
Lather sewing kit prices 

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#68]
Haha the price for a kit is a bargain 👌🤣
![20210523_150849](https://user-images.githubusercontent.com/81928410/119261756-12a48000-bbd9-11eb-9ddc-42cf118b5615.jpg)

**Comment by MrWolfGaming** [comment]
![20210523_151141](https://user-images.githubusercontent.com/81928410/119261792-3ec00100-bbd9-11eb-88bd-bffa4d2351b4.jpg)


I will burn the money

**Comment by MrWolfGaming** [comment]
Also it won't take the kit when you sell it so you can sell it how many times you want. 

I quess there is alot of nasty riche ppl on the server now 🤣

**Comment by 42MonthsAfter** [comment]
Just tested and this one is fixed.
