### ISSUE TITLE
Server not showing up 

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#7]
It did happen again. The server did go down for restart 6 in the morning swedish time (though it shall be your time) 
And did not come back up and a few hours later it was back up again whiteout you posting a new restart. 

I think the server sometimes is running but something stops it from showing up on steam

**Comment by 42MonthsAfter** [comment]
Are you able to find it on DZSA or is it not showing up AT ALL?

**Comment by MrWolfGaming** [comment]
I did check on Mrs Wolfs pc cus she has DZSA installed and it says offline. 
When this happed last time, Cowboy culdent finde it ether and then all the sudden it was back without you doing anything.

Dont know if it is the port for the server listing that dosent open every time it restarts or somthing.

and the server is ment to restart 06am, 12, 06am and then 12 your time isent it?
Cus every time this happens it happens thos hours but swedish time

**Comment by 42MonthsAfter** [comment]
Got it, thats interesting. I literally have alarms to look at 6, 12, 18, 00 to make sure its up. Sounds like something isn't working right though. I will dig into it this weekend.

**Comment by MrWolfGaming** [comment]
So the timing of restarts are right just need to figur out why it dosent show up but is online

**Comment by 42MonthsAfter** [comment]
Did the update to the server a couple days ago resolve this issue?

**Comment by MrWolfGaming** [comment]
So far that problem hasn't happened again 😊
