### ISSUE TITLE
Stuff did despawn

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#72]
One of my Rifel Safe did despawn with 250k and 2 M16A1 in it.
All the other Rifel Safe we have are still there exept the black one i hade in my tent

**Comment by MrWolfGaming** [comment]
soo after a closer look. 1 tool bench and 1 harddig has also despawnd and 1 green house did go away to

**Comment by 42MonthsAfter** [comment]
I found the error here very quickly, it was on my part.
I removed:
    <nominal>0</nominal>
from those entries somehow. 

Let me know what you lost and I'll get you back!
