### ISSUE TITLE
Stuff have despawn sens the rollback

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#75]
So Mrs Wolf did just login and her GAZ  i gone, and 1 of the large tents and 95% of our harddigs and some rifel racks and safes have also despawnd

**Comment by 42MonthsAfter** [comment]
Just to be clear, this from BEFORE last nights updates. Not sense. As in, it was there this morning and now it is going.

**Comment by MrWolfGaming** [comment]
We was on until you made the quick restart like 11.45pm for us and the stuff was there when we got kicked off the server cus of the restart and then we went to bed. So not 100% sure when it happened 🤔

**Comment by 42MonthsAfter** [comment]
Minus the flagpoll which i think was something else, how has despawn been?

**Comment by MrWolfGaming** [comment]
Minus the flagpoll?

**Comment by 42MonthsAfter** [comment]
I think the flag pole was a different issue.
