### ISSUE TITLE
Cant fill cantens or jerry cans in the open waters

### ISSUE THREAD

**Issue by bluecollarboysgaming** [42MonthsAfter/server#76]
cant fill canteens or jerrry cans in the ponds streams lakes or ocean

**Comment by MrWolfGaming** [comment]
i think i know whats wrung with this one. Salt water cant be used.
I have tryed this out a bit. 
All water sourse that is connected to the sea cant be filled in a canteen but all lakes can be used.

**Comment by 42MonthsAfter** [comment]
Thanks for the update @MrWolfGaming
