### ISSUE TITLE
Car Lock System

### ISSUE THREAD

**Issue by Galaxy-Panda** [42MonthsAfter/server#79]
Sarka is only giving option to lock and un lock with keypad lock. will no longer give the option to get in nor access invtory or open doors. was working 5 minutes ago. we got out to loot and now this.

**Comment by 42MonthsAfter** [comment]
Let me know the next time you are on, i haven't seen this issue but there are small zones for each action

Can check it out

**Comment by 42MonthsAfter** [comment]
So I have have an interesting bug where I have had to have the car lock on my person for it to work. Not related to this I don't think but still the same mod. Will update post on the creator's discord.

**Comment by 42MonthsAfter** [comment]
Fixed rolled into 9.0.2
