### ISSUE TITLE
Mele weapons

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#83]
Is there a way to pump up how much dmg a mele weapon do?
Mrs Wolf did try to hit one to death with a metal bat and she did hit it like 20 times befor she had to shoot it 4 times to kill it.
So i think mele weapons need a buff so we can use them.

**Comment by 42MonthsAfter** [comment]
So interestingly I can't find a way to boost JUST the melle weapon strength. I'm going to post on the creator's discord to see if we can't get it figured out.

**Comment by 42MonthsAfter** [comment]
I have adjusted so that the zombies should be able to be clobbered with more damage now. Reduced zombie resistance to melle by 50%. 

Combined with the adjustments to those few insane zombies, this should balance out. Rolling out with the 9.0.2 update tonight.
