### ISSUE TITLE
Super Zombies

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#95]
Altho i like them but some dont. There is still some models of Zombies that can take a hole mag of bullets without going down.
Well add on what ones that are still doing that as i stumbel on them.

**Comment by 42MonthsAfter** [comment]
Have you tried more headshots? Cause Zombies are known for being dropped with headshots.  

You can literally spray them in the body all day with no result...

**Comment by MrWolfGaming** [comment]
Yea ofc I have 😊 the super zombie can take up to 10 shoots in the face 😎
