### ISSUE TITLE
Super zombie VS Car

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/server#96]
i know some are complaining on radiators brake with one hit with a zombie.
Can in be that if you hit a super zombie that it register a super hit to the car cus they have so much HP?
usely i can hit 5-10 zombies with my LR befor the radiator brakes but last night when i did hit a super zombie it went from prestine to badly damged in 1 hit.
or it was just bad luck ^^

**Comment by 42MonthsAfter** [comment]
So it works on probability, not number of hits. 

Didn't want people to be able to game it by being like "I have 4 more hits to go".  The chance of it happening depends on the car, larger = stronger, that being said it is a roll of the dive every time.

**Comment by MrWolfGaming** [comment]
Ahh nice, like in reality some times a bigger hit dose nothing and sometimes a small hit kills the car
