### ISSUE TITLE
Scavenger Hunt

### ISSUE THREAD

**Issue by Jakedickinson1** [42MonthsAfter/server#98]
So did the scavenger hunt for the oldtown police department.... there was literally two pistols and a box of 9 mil....
Idk if the stuff despawned or if that was the intent but I didn't know if it was bugged or not. The note said a "Large Ammo Crate".

**Comment by 42MonthsAfter** [comment]
Did you knock down the wall? Or could it have been claimed before you got there?

We are having an issue with people not taking notes with them so others are restarting finished ones.
